### ISSUE TITLE
I've cloned the repo but...

### ISSUE THREAD

**Issue by ryanmitchell** [Oleafeon/issue-ideaal#1]
I could really do with some steps to reproduce the issues and some initial data to seed. Are you able to share a sql file I can import or anything like that to get me to the issue quicker?

**Comment by Oleafeon** [comment]
[ideaal.zip](https://github.com/Oleafeon/issue-ideaal/files/8398073/ideaal.zip)
this is my current sql file

**Comment by Oleafeon** [comment]
you could be experincing an error with font awesome but you can remove that package off this branch for now we can later readd it

**Comment by ryanmitchell** [comment]
Perfect thanks. I've pushed up some fixed to https://github.com/statamic/eloquent-driver/pull/42

If you have any more problems raise an issue here with the detail and I'll be notified and should be able to fix

**Comment by Oleafeon** [comment]
Collections is working now
but i have found some issues
Ordening is not being saved

Navigations works

Origin in globals is fixed

Creating a form still has the same issue

i have updated this repository with the new patch

here is my new sql file
[ideaal.zip](https://github.com/Oleafeon/issue-ideaal/files/8398247/ideaal.zip)

**Comment by ryanmitchell** [comment]
As for ordering, if you can give me a screencast of the issue I'll try and find time to look into it further when I get more time.

**Comment by Oleafeon** [comment]
https://www.loom.com/share/4f0303cc066d43b6a71e6b0382ab02b5 here you go

**Comment by ryanmitchell** [comment]
Got you now - thought you meant something else.
See https://github.com/ryanmitchell/eloquent-driver/commit/5d4a7b95d0b579b204fe811fbd47928d2e048279

**Comment by Oleafeon** [comment]
yes that worked

**Comment by ryanmitchell** [comment]
The taxonomy issue is that you need to include this PR in statamic/cms - https://github.com/statamic/cms/pull/5844/files

**Comment by ryanmitchell** [comment]
And I've fixed the origin issue here: https://github.com/statamic/eloquent-driver/pull/42/commits/00563fe2c62be9beadf5a9c9bb3b1b1ff7c2bd1e

**Comment by Oleafeon** [comment]
> The taxonomy issue is that you need to include this PR in statamic/cms - https://github.com/statamic/cms/pull/5844/files

this is fixed



> And I've fixed the origin issue here: [statamic/eloquent-driver@00563fe](https://github.com/statamic/eloquent-driver/commit/00563fe2c62be9beadf5a9c9bb3b1b1ff7c2bd1e)

i still get the same error

**Comment by Oleafeon** [comment]
i also saw this on the 404 page
![image](https://user-images.githubusercontent.com/20043831/164248110-4f7fbd6d-3aa2-451a-a679-8c2fbe67d751.png)

**Comment by ryanmitchell** [comment]
I’m going to let these get picked up by the core team - I’ve done as much as I can to support things to this point.

**Comment by ryanmitchell** [comment]
> > The taxonomy issue is that you need to include this PR in statamic/cms - https://github.com/statamic/cms/pull/5844/files
> 
> this is fixed
> 
> > And I've fixed the origin issue here: [statamic/eloquent-driver@00563fe](https://github.com/statamic/eloquent-driver/commit/00563fe2c62be9beadf5a9c9bb3b1b1ff7c2bd1e)
> 
> i still get the same error

You need to set origin to null in the json for that localisation in the database

**Comment by Oleafeon** [comment]
yes that worked

**Comment by Oleafeon** [comment]
ill just have globals not setup with origin then

now the only error i saw was `Call to a member function collection() on null`

**Comment by Oleafeon** [comment]
yes i saw thank you
